name: 02 Workflow Triggers
on:
  pull_request:
  workflow_dispatch:

jobs:
  echo-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Triggered
        run: echo "This workflow was triggered by a ${{ github.event_name }} event!"
