name: 03 Workflow Runners
on: workflow_dispatch

defaults:
  run:
    shell: bash

jobs:
  ubuntu-job:
    runs-on: ubuntu-latest
    steps:
      - name: Ubuntu Runner
        run: |
          echo "I am an Ubuntu runner."
          echo "This job is running on $RUNNER_OS."

  windows-job:
    runs-on: windows-latest
    steps:
      - name: Windows Runner
        run: |
          echo "I am a Windows runner."
          echo "This job is running on $RUNNER_OS."

  macos-job:
    runs-on: macos-latest
    steps:
      - name: macOS Runner
        run: |
          echo "I am a MacOS Runner"
          echo "This job is running on $RUNNER_OS."