name: 06 Contexts
run-name: Contexts Demo - ${{ github.workflow }} - ${{ github.run_id }} - ${{ inputs.debug }}
on:
  workflow_dispatch:
    inputs:
      debug:
        required: false
        default: false
        type: boolean

env:
  GLOBAL_ENV_VAR: "I am a global environment variable"
  OVERWRITTEN_VAR: "I will be overridden"

jobs:
  echo-data:
    env:
      JOB_ENV_VAR: "I am a job-level environment variable"
      OVERWRITTEN_VAR: "I am the overridden variable at job level"
    runs-on: ubuntu-latest
    steps:
      - name: Echo GitHub Context
        env:
          STEP_ENV_VAR: "I am a step-level environment variable"
          OVERWRITTEN_VAR: "I am the overridden variable at step level"
        run: |
          echo "GitHub Context:"
          echo "${{ toJson(github) }}"
          echo "Step Environment Variable: ${{ env.STEP_ENV_VAR }}"
          echo "Overwritten Variable: ${{ env.OVERWRITTEN_VAR }}"
      - name: Echo Runner Context
        run: |
          echo "Runner Context:"
          echo "${{ toJson(runner) }}"
      - name: Echo Job Context
        run: |
          echo "Job Context:"
          echo "${{ toJson(job) }}"
      - name: Echo Steps Context
        run: |
          echo "Steps Context:"
          echo "${{ toJson(steps) }}"
      - name: Echo Env Context
        run: |
          echo "Env Context:"
          echo "${{ toJson(env) }}"
      - name: Echo Variable
        run: |
          echo "Variable Context:"
          echo "${{ toJson(vars) }}"
      - name: Echo Secrets
        run: |
          echo "Secrets Context:"
          echo "${{ toJson(secrets) }}"

